#! /bin/bash

eval 'set -- $1'  # strip
echo "Releasing with resalloc ticket data: $1"

cd /root/openscanhub
podman exec -it osh-hub env PYTHONPATH=.:kobo python3 osh/hub/scripts/osh-resalloc --delete-worker $1
